VeryGoodOpenSource/flame_behaviors

lib/src/entity.dart
=> fix: missing arguments on entity

lib/src/behaviors/behavior.dart, test/src/behaviors/behavior_test.dart
Proxy `debugMode` from parent entity to behaviors. This allows developers to just enable it on the entity itself for testing purposes.
=> feat: proxy `debugMode` down to individual behaviors

lib/src/entity.dart, test/src/entity_test.dart
Add an easy method for checking if an entity has a certain behavior.
=> feat: add `hasBehavior` method

lib/src/behaviors/propagating_collision_behavior.dart, lib/src/entity.dart, test/helpers/helpers.dart, test/helpers/throws_behavior_not_found_for.dart, test/src/behaviors/propagating_collision_behavior_test.dart, test/src/entity_test.dart
This PR changes the API slightly to remove nullable values and adds extra documentation to the API to reflect internally workings of the component tree.
=> feat: make the internal find behavior logic more clear on when it can find something

README.md, lib/src/entity.dart, pubspec.yaml
Make the `README` more descriptive so that it is more clear what is possible in the package.
=> docs: make README more descriptive

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/build.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/ci.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/performance.md, .github/ISSUE_TEMPLATE/refactor.md, .github/ISSUE_TEMPLATE/revert.md, .github/ISSUE_TEMPLATE/style.md, .github/ISSUE_TEMPLATE/test.md, CONTRIBUTING.md
- chore: add contributing.md and issue templates
=> chore: add contributing.md and issue templates

CHANGELOG.md, pubspec.yaml
=> chore: v0.1.0

example/lib/behaviors/behaviors.dart, example/lib/behaviors/rotation_behavior.dart, example/lib/behaviors/screen_collision_behavior.dart, example/lib/entities/circle/circle.dart, example/lib/entities/rectangle/rectangle.dart, example/lib/main.dart, lib/src/behaviors/propagating_collision_behavior.dart, test/src/behaviors/propagating_collision_behavior_test.dart
=> fix: `PropagatingCollisionBehavior` should also work for non entity components

.github/workflows/flame_behaviors.yaml
- ci: use semantic-pull-request workflow
=> ci: use semantic-pull-request workflow

README.md
=> docs: add missing word to the pong text

analysis_options.yaml, example/analysis_options.yaml, example/pubspec.yaml, pubspec.yaml
=> feat: update version constraints

.github/cspell.json, README.md, docs/collision-detection.md, docs/conventions/coding-conventions.md, docs/conventions/naming-conventions.md, docs/getting-started.md, docs/input-behaviors.md, packages/flame_behaviors/README.md, packages/flame_behaviors/example/lib/behaviors/behaviors.dart, packages/flame_behaviors/example/lib/behaviors/spawning_behavior.dart, packages/flame_behaviors/example/lib/entities/behaviors/behaviors.dart, packages/flame_behaviors/example/lib/entities/behaviors/moving_behavior.dart, packages/flame_behaviors/example/lib/entities/behaviors/rotating_behavior.dart, packages/flame_behaviors/example/lib/entities/behaviors/screen_colliding_behavior.dart, packages/flame_behaviors/example/lib/entities/circle/behaviors/dragging_behavior.dart, packages/flame_behaviors/example/lib/entities/circle/circle.dart, packages/flame_behaviors/example/lib/entities/rectangle/behaviors/behaviors.dart, packages/flame_behaviors/example/lib/entities/rectangle/behaviors/circle_colliding_behavior.dart, packages/flame_behaviors/example/lib/entities/rectangle/behaviors/freezing_behavior.dart, packages/flame_behaviors/example/lib/entities/rectangle/behaviors/rectangle_colliding_behavior.dart, packages/flame_behaviors/example/lib/entities/rectangle/rectangle.dart, packages/flame_behaviors/example/lib/main.dart, packages/flame_behaviors/lib/src/entity.dart, packages/flame_behaviors/pubspec.yaml
Reworking the documentation to be more useful and structured.
Closes #25
=> docs: rework docs into its own directory

packages/flame_behaviors/CHANGELOG.md, packages/flame_behaviors/pubspec.yaml
=> chore: flame_behaviors-v0.2.0

.github/workflows/flame_behaviors.yaml, packages/flame_behaviors/analysis_options.yaml, packages/flame_behaviors/example/analysis_options.yaml, packages/flame_behaviors/example/lib/entities/circle/circle.dart, packages/flame_behaviors/example/lib/entities/rectangle/rectangle.dart, packages/flame_behaviors/example/pubspec.yaml, packages/flame_behaviors/lib/flame_behaviors.dart, packages/flame_behaviors/lib/src/behaviors/input/input.dart, packages/flame_behaviors/pubspec.yaml
Upgrade `very_good_analysis` to v4.0.0
=> chore: upgrade analysis dependency

.github/cspell.json, docs/input-behaviors.md, packages/flame_behaviors/example/lib/behaviors/spawning_behavior.dart, packages/flame_behaviors/example/lib/entities/circle/behaviors/dragging_behavior.dart, packages/flame_behaviors/example/lib/entities/rectangle/behaviors/freezing_behavior.dart, packages/flame_behaviors/example/lib/main.dart, packages/flame_behaviors/lib/src/behaviors/behavior.dart, packages/flame_behaviors/lib/src/behaviors/input/draggable_behavior.dart, packages/flame_behaviors/lib/src/behaviors/input/tappable_behavior.dart, packages/flame_behaviors/pubspec.yaml, packages/flame_behaviors/test/src/behaviors/behavior_test.dart, packages/flame_behaviors/test/src/entity_test.dart
=> feat(flame_behaviors)!: migrate to flame v1.7.0

packages/flame_behaviors/CHANGELOG.md, packages/flame_behaviors/pubspec.yaml
=> chore(flame_behaviors): v0.3.0

packages/flame_steering_behaviors/CHANGELOG.md, packages/flame_steering_behaviors/pubspec.yaml
=> chore(flame_steering_behaviors): v0.1.0

docs/getting-started.md
=> docs: fix missing links

docs/collision-detection.md
=> docs: fix typo in docs

.github/workflows/flame_behaviors.yaml, .github/workflows/flame_steering_behaviors.yaml, packages/flame_behaviors/example/pubspec.yaml, packages/flame_behaviors/pubspec.yaml, packages/flame_steering_behaviors/example/pubspec.yaml, packages/flame_steering_behaviors/pubspec.yaml
=> chore: tighten dependencies

packages/flame_steering_behaviors/example/pubspec.yaml
**READY**
Both dependencies require the Dart 3.5 SDK as from #64.
=> chore: tighten flame_steering_behaviors example

.github/workflows/flame_behaviors_pub_piublish.yaml, .github/workflows/flame_steering_behaviors_pub_publish.yaml
**READY**
Related to #63
Adds the [Automated Publishing](https://dart.dev/tools/pub/automated-publishing) workflows to both packages (flame_behaviors and flame_steering_behaviors).
The pertinent configuration in `pub.dev` has also been completed.
=> ci: add pub_publish workflows

packages/flame_behaviors/lib/src/behaviors/propagating_collision_behavior.dart, packages/flame_behaviors/lib/src/entity.dart, packages/flame_behaviors/pubspec.yaml
**READY**
Support for Flame 1.19, that introduced a breaking change that affects the package.
=> feat: Flame 1.19 support

packages/flame_behaviors/CHANGELOG.md, packages/flame_behaviors/pubspec.yaml, packages/flame_behaviors/tool/release_ready.sh
=> chore(flame_behaviors): v1.2.0

packages/flame_steering_behaviors/lib/src/behaviors/separation_behavior.dart, packages/flame_steering_behaviors/pubspec.yaml
**READY**
Tighten dependencies.
=> chore(flame_steering_behaviors): tighten dependencies

.github/workflows/flame_behaviors_pub_publish.yaml, .github/workflows/flame_steering_behaviors_pub_publish.yaml
=> chore: update pub publish scripts
